export const products = [
  {
    id: 1,
    name: "The Royal Silk Gown",
    price: 12999,
    category: "Dresses",
    image: "https://www.neetalulla.com/cdn/shop/files/Neeta-mam-day-1_1040-copy.jpg?v=1760291684&width=1800",
    colors: ["Red", "Black"],
    sizes: ["S", "M", "L"],
    description: "Elegant silk gown with a royal finish, perfect for evening galas.",
    isNew: true,
  },
  {
    id: 2,
    name: "Velvet Evening Blazer",
    price: 8499,
    category: "Outerwear",
    image: "https://www.neetalulla.com/cdn/shop/files/77A8928f.webp?v=1723794495&width=1800",
    colors: ["Navy", "Black"],
    sizes: ["M", "L", "XL"],
    description: "Premium velvet blazer tailored for a sharp, sophisticated look.",
    isNew: false,
  },
  {
    id: 3,
    name: "Champagne Gold Saree",
    price: 15999,
    category: "Ethnic",
    image: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=1000&auto=format&fit=crop",
    colors: ["Gold"],
    sizes: ["Free Size"],
    description: "Handwoven champagne gold saree with intricate metallic embroidery.",
    isNew: true,
  },
  {
    id: 4,
    name: "Minimalist Linen Trousers",
    price: 3499,
    category: "Bottoms",
    image: "https://www.neetalulla.com/cdn/shop/files/11_1.webp?v=1717065707&width=1800",
    colors: ["Beige", "White"],
    sizes: ["S", "M", "L", "XL"],
    description: "Breathable linen trousers designed for comfort and effortless style.",
    isNew: false,
  },
  {
    id: 5,
    name: "Scarlet Midi Dress",
    price: 5999,
    category: "Dresses",
    image: "https://images.unsplash.com/photo-1539008835657-9e8e9680c956?q=80&w=1000&auto=format&fit=crop",
    colors: ["Red"],
    sizes: ["XS", "S", "M"],
    description: "A stunning scarlet midi dress that captures attention with every step.",
    isNew: true,
  },
  {
    id: 6,
    name: "Classic Trench Coat",
    price: 9999,
    category: "Outerwear",
    image: "https://www.neetalulla.com/cdn/shop/files/Ecru-Satin-Concept-Saree-Set-with-Jacket-1.jpg?v=1736597119&width=1800",
    colors: ["Beige", "Black"],
    sizes: ["S", "M", "L"],
    description: "Timeless trench coat featuring water-resistant fabric and a belted waist.",
    isNew: false,
  },
];
